services:
  database:
    image: mysql:8.0
    container_name: payment-db
    restart: always
    ports:
      - 3309:3306
    environment:
      TZ: Asia/Bangkok
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: payment-db-service
