services:
  database:
    image: postgres
    container_name: payment-db
    restart: always
    ports:
      - 5434:5432
    environment:
      TZ: Asia/Bangkok
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: payment-db-service
